In [1]:
import numpy as np

In [2]:
class FOS:
    def __init__(self, n_class):
        self. n_class = n_class
    
    def mean(self, X, low, high):
        return X[low-1: high].mean(axis=0)
    
    def varition(self, X, low, high):
        data = X[low-1: high]
        devia = data - self.mean(X, low, high)
        vari = (devia ** 2).sum()
        return vari
    
    def fit_transform(self, X, k):
        table = self.split_k(X, k)
        split_points = table[k, len(X)][1]
        split_points = np.insert(split_points, 0, 1)
        split_points = np.append(split_points, len(X))
        split_res = [[split_points[i], split_points[i+1]] for i in range(len(split_points)-1)]
        return split_points, len(split_points), table
    
    def split_k(self, X, k):
        n = X.shape(0)
        table = np.zeros((k+1, n+1), dtype='object')
        for j in range(2, n+1):
            table[2, j] = split_2(X, j)
        for i in range(3, k+1):
            for j in range(i, n+1):
                cache = {}
                for m in range(i-1, j):
                    vari = table[i-1, m][0] + self.varition(X, j, n)
                    cache[vari] = m
                minvari = min(cache.keys())
                table[i, j] = (minvari, np.append(table[i-1, m][1], m+1))
        return table
    
    def split_2(self, X, endp):
        loss2cutp = {}
        for i in range(2, endp+1):
            loss2cutp[self.varition(X, 1, i-1) + self.varition(X, i, endp)] = i
        min_loss = min(loss2cutp.keys())
        min_cutp = loss2cutp[min_loss]
        res = (min_loss, np.array([min_cutp]))
        return res
    
        

SyntaxError: unexpected EOF while parsing (<ipython-input-2-7d8360290289>, line 2)

In [9]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.insert(a, 0, 10)

array([10,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [17]:
a = np.arange(4).reshape(2, 2)

In [18]:
a

array([[0, 1],
       [2, 3]])

In [20]:
a.sum()

6